// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

use crate::Auth;
use std::fmt;

glib::wrapper! {
    #[doc(alias = "SoupAuthNTLM")]
    pub struct AuthNTLM(Object<ffi::SoupAuthNTLM>) @extends Auth;

    match fn {
        type_ => || ffi::soup_auth_ntlm_get_type(),
    }
}

impl AuthNTLM {}

impl fmt::Display for AuthNTLM {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("AuthNTLM")
    }
}
