// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

use crate::WebsocketExtension;
use std::fmt;

glib::wrapper! {
    #[doc(alias = "SoupWebsocketExtensionDeflate")]
    pub struct WebsocketExtensionDeflate(Object<ffi::SoupWebsocketExtensionDeflate, ffi::SoupWebsocketExtensionDeflateClass>) @extends WebsocketExtension;

    match fn {
        type_ => || ffi::soup_websocket_extension_deflate_get_type(),
    }
}

impl WebsocketExtensionDeflate {}

pub const NONE_WEBSOCKET_EXTENSION_DEFLATE: Option<&WebsocketExtensionDeflate> = None;

impl fmt::Display for WebsocketExtensionDeflate {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("WebsocketExtensionDeflate")
    }
}
